language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

before_install:
  - rm -rf .php-version

before_script:
  - composer self-update
  - composer install --prefer-source

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

script:
  - composer test
