language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

before_script:
  - composer install --dev

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

script:
  - composer test