language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

before_install:
  - rm -rf .php-version

before_script:
  - composer install

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    # for https://github.com/travis-ci/travis-ci/issues/4897
    - php: 5.6
    - php: hhvm

    - php: nightly

script:
  - composer test
